import type { AppProps } from "next/app";

import "@/styles/global/globals.css";
import "@/styles/global/fonts.css";
import "react-toastify/dist/ReactToastify.css";

import Head from "next/head";
import ToastContainerComponent from "@/components/toasts/ToastContainer";

export default function App({ Component, pageProps }: AppProps) {
    return (
        <>
            <Head>
                <title>Registration Form</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
                <link
                    href="https://fonts.googleapis.com/icon?family=Material+Icons"
                    rel="stylesheet"
                />
            </Head>
            <Component {...pageProps} />
            <ToastContainerComponent />
        </>
    );
}
